r8822cs-core-y += \
		rtw_cmd.o \
		rtw_security.o \
		rtw_debug.o \
		rtw_io.o \
		rtw_ioctl_query.o \
		rtw_ioctl_set.o \
		rtw_ieee80211.o \
		rtw_mlme.o \
		rtw_mlme_ext.o \
		rtw_mi.o \
		rtw_wlan_util.o \
		rtw_vht.o \
		rtw_pwrctrl.o \
		rtw_rf.o \
		rtw_chplan.o \
		rtw_recv.o \
		rtw_sta_mgt.o \
		rtw_ap.o \
		mesh/rtw_mesh.o \
		mesh/rtw_mesh_pathtbl.o \
		mesh/rtw_mesh_hwmp.o \
		rtw_xmit.o	\
		rtw_p2p.o \
		rtw_rson.o \
		rtw_tdls.o \
		rtw_br_ext.o \
		rtw_iol.o \
		rtw_sreset.o \
		rtw_btcoex_wifionly.o \
		rtw_btcoex.o \
		rtw_beamforming.o \
		rtw_odm.o \
		rtw_rm.o \
		rtw_rm_fsm.o \
		efuse/rtw_efuse.o 

obj-$(CONFIG_RTL8822CS_CORE_DRV) += r8822cs-core.o
obj-$(CONFIG_SDIO_HCI) += rtw_sdio.o
obj-$(CONFIG_MP_INCLUDED) += rtw_mp.o
